version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=config/whyq-lunch-evaluation-777f06764b4e.json
      - GOOGLE_CLOUD_PROJECT=whyq-lunch-evaluation
  frontend:
    build: ./frontend
    ports:
      - '3000:80'