version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/usr/share/nginx/html